const macIcon = (...parts) =>
  `/mac_icons/${parts.map((part) => encodeURIComponent(part)).join("/")}`

export const MAC_ICONS = {
  finder: macIcon("icons", "finder.png"),
  apps: macIcon("icons", "apps.png"),
  safari: macIcon("icons", "safari.png"),
  messages: macIcon("icons", "messages.png"),
  mail: macIcon("icons", "mail.png"),
  maps: macIcon("icons", "maps.png"),
  photos: macIcon("icons", "photos.png"),
  facetime: macIcon("icons", "facetime.png"),
  phone: macIcon("icons", "phone.png"),
  calendar: macIcon("icons", "calendar.png"),
  contacts: macIcon("icons", "contacts.png"),
  notes: macIcon("icons", "notes.png"),
  reminders: macIcon("icons", "reminders.png"),
  music: macIcon("icons", "music.png"),
  systemSettings: macIcon("icons", "system settings.png"),
  podcasts: macIcon("icons", "podcasts.png"),
  tv: macIcon("icons", "tv.png"),
  appStore: macIcon("icons", "app store.png"),
  trashEmpty: macIcon("icons", "trash (empty).png"),
  trashFull: macIcon("icons", "trash (full) (upscale edit).png"),
  textEdit: macIcon("utils", "textedit.png"),
  terminal: macIcon("utils", "terminal.png"),
  preview: macIcon("utils", "preview.png"),
  siri: macIcon("icons", "siri.png"),
  internalDrive: macIcon("drives", "internal.png"),
  externalDrive: macIcon("drives", "external.png"),
  removableDrive: macIcon("drives", "removable.png"),
  backupDrive: macIcon("drives", "backup.png"),
  networkDrive: macIcon("drives", "network (not drive).png"),
  appStub: macIcon("other", "automator application stub.png"),
}

const toAppLabel = (fileName) =>
  fileName
    .replace(/\.png$/i, "")
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ")

const toAppId = (fileName) =>
  `stub_${fileName.replace(/\.png$/i, "").replace(/[^a-z0-9]+/gi, "_").toLowerCase()}`

/**
 * Remaining mac_icons PNGs shown as non-interactive stubs in Apps / Applications.
 * Paths are relative to public/mac_icons (folder/file.png).
 */
export const STUB_APP_ICON_SOURCES = [
  ["icons", "books.png"],
  ["icons", "calculator.png"],
  ["icons", "clock.png"],
  ["icons", "find my.png"],
  ["icons", "freeform.png"],
  ["icons", "games.png"],
  ["icons", "home.png"],
  ["icons", "image playground.png"],
  ["icons", "iphone mirroring.png"],
  ["icons", "journal.png"],
  ["icons", "news.png"],
  ["icons", "passwords.png"],
  ["icons", "photo booth.png"],
  ["icons", "siri.png"],
  ["icons", "stocks.png"],
  ["icons", "voice memos.png"],
  ["icons", "weather.png"],
  ["utils", "activity monitor.png"],
  ["utils", "audio midi setup.png"],
  ["utils", "automator.png"],
  ["utils", "bluetooth file exchange.png"],
  ["utils", "chess.png"],
  ["utils", "colorsync utility.png"],
  ["utils", "console.png"],
  ["utils", "dictionary.png"],
  ["utils", "digital color meter.png"],
  ["utils", "disk utility.png"],
  ["utils", "font book.png"],
  ["utils", "grapher.png"],
  ["utils", "image capture.png"],
  ["utils", "migration assistant.png"],
  ["utils", "mission control.png"],
  ["utils", "print center.png"],
  ["utils", "quicktime player.png"],
  ["utils", "screen sharing.png"],
  ["utils", "screenshot.png"],
  ["utils", "script editor.png"],
  ["utils", "shortcuts.png"],
  ["utils", "stickies.png"],
  ["utils", "system information.png"],
  ["utils", "time machine.png"],
  ["utils", "tips.png"],
  ["utils", "voiceover utility.png"],
  ["other", "accessibility reader.png"],
  ["other", "apple diagnostics.png"],
  ["other", "apple script utility.png"],
  ["other", "archive utility.png"],
  ["other", "avb configurator.png"],
  ["other", "batteries.png"],
  ["other", "control center.png"],
  ["other", "desk view.png"],
  ["other", "directory utility.png"],
  ["other", "dvd player.png"],
  ["other", "erase assistant.png"],
  ["other", "expansion slot utility.png"],
  ["other", "feedback assistant.png"],
  ["other", "folder actions setup.png"],
  ["other", "game center.png"],
  ["other", "games alt.png"],
  ["other", "icloud.png"],
  ["other", "install command line tools.png"],
  ["other", "installer.png"],
  ["other", "keychain access.png"],
  ["other", "magnifier.png"],
  ["other", "medical imaging calibrator.png"],
  ["other", "music recognition.png"],
  ["other", "pass viewer.png"],
  ["other", "pip agent.png"],
  ["other", "pro display calibrator.png"],
  ["other", "screen time.png"],
  ["other", "setup assistant.png"],
  ["other", "spotlight.png"],
  ["other", "ticket viewer.png"],
  ["other", "universal control.png"],
  ["other", "wallpaper.png"],
  ["other", "widgetkit simulator.png"],
  ["other", "wireless diagnostics.png"],
]

export const STUB_APPS = STUB_APP_ICON_SOURCES.map(([folder, fileName]) => ({
  appId: toAppId(fileName),
  id: toAppId(fileName),
  name: `${toAppLabel(fileName)}.app`,
  label: toAppLabel(fileName),
  icon: macIcon(folder, fileName),
  type: "app",
  isStub: true,
  date: "2026-06-15T10:00:00Z",
  size: 12_000_000,
}))
